package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Annee generated by hbm2java
 */
@Entity
@Table(name = "annee", catalog = "ministere")
public class Annee implements java.io.Serializable {

	private int annee;
	private Set<AvoirBudorg> avoirBudorgs = new HashSet<AvoirBudorg>(0);

	public Annee() {
	}

	public Annee(int annee) {
		this.annee = annee;
	}

	public Annee(int annee, Set<AvoirBudorg> avoirBudorgs) {
		this.annee = annee;
		this.avoirBudorgs = avoirBudorgs;
	}

	@Id
	@Column(name = "ANNEE", unique = true, nullable = false)
	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	@Transient
	public String getAnneeS() {
		return "" + annee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annee")
	public Set<AvoirBudorg> getAvoirBudorgs() {
		return this.avoirBudorgs;
	}

	public void setAvoirBudorgs(Set<AvoirBudorg> avoirBudorgs) {
		this.avoirBudorgs = avoirBudorgs;
	}

}
