package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AvoirBudorg generated by hbm2java
 */
@Entity
@Table(name = "avoir_budorg", catalog = "ministere")
public class AvoirBudorg implements java.io.Serializable {

	private AvoirBudorgId id;
	private Organisme organisme;
	private Annee annee;
	private Double valBudMis;
	private String refValBudMis;
	private String arefValBudMis;
	private double valBudTrans;
	private String refValBudTrans;
	private String arefValBudTrans;
	private Date dateValeurs;

	public AvoirBudorg() {
	}

	public AvoirBudorg(AvoirBudorgId id, Organisme organisme, Annee annee,
			String refValBudMis, String arefValBudMis, double valBudTrans,
			String refValBudTrans, String arefValBudTrans) {
		this.id = id;
		this.organisme = organisme;
		this.annee = annee;
		this.refValBudMis = refValBudMis;
		this.arefValBudMis = arefValBudMis;
		this.valBudTrans = valBudTrans;
		this.refValBudTrans = refValBudTrans;
		this.arefValBudTrans = arefValBudTrans;
	}

	public AvoirBudorg(AvoirBudorgId id, Organisme organisme, Annee annee,
			Double valBudMis, String refValBudMis, String arefValBudMis,
			double valBudTrans, String refValBudTrans, String arefValBudTrans,
			Date dateValeurs) {
		this.id = id;
		this.organisme = organisme;
		this.annee = annee;
		this.valBudMis = valBudMis;
		this.refValBudMis = refValBudMis;
		this.arefValBudMis = arefValBudMis;
		this.valBudTrans = valBudTrans;
		this.refValBudTrans = refValBudTrans;
		this.arefValBudTrans = arefValBudTrans;
		this.dateValeurs = dateValeurs;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeOrg", column = @Column(name = "CODE_ORG", nullable = false, length = 6)),
			@AttributeOverride(name = "annee", column = @Column(name = "ANNEE", nullable = false)),
			@AttributeOverride(name = "numeroOrdreBudOrg", column = @Column(name = "NUMERO_ORDRE_BUD_ORG", nullable = false)),
			@AttributeOverride(name = "codeUtil", column = @Column(name = "CODE_UTIL", nullable = false, length = 8)) })
	public AvoirBudorgId getId() {
		return this.id;
	}

	public void setId(AvoirBudorgId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ORG", nullable = false, insertable = false, updatable = false)
	public Organisme getOrganisme() {
		return this.organisme;
	}

	public void setOrganisme(Organisme organisme) {
		this.organisme = organisme;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ANNEE", nullable = false, insertable = false, updatable = false)
	public Annee getAnnee() {
		return this.annee;
	}

	public void setAnnee(Annee annee) {
		this.annee = annee;
	}

	@Column(name = "VAL_BUD_MIS", precision = 22, scale = 0)
	public Double getValBudMis() {
		return this.valBudMis;
	}

	public void setValBudMis(Double valBudMis) {
		this.valBudMis = valBudMis;
	}

	@Column(name = "REF_VAL_BUD_MIS", nullable = false, length = 30)
	public String getRefValBudMis() {
		return this.refValBudMis;
	}

	public void setRefValBudMis(String refValBudMis) {
		this.refValBudMis = refValBudMis;
	}

	@Column(name = "AREF_VAL_BUD_MIS", nullable = false, length = 60)
	public String getArefValBudMis() {
		return this.arefValBudMis;
	}

	public void setArefValBudMis(String arefValBudMis) {
		this.arefValBudMis = arefValBudMis;
	}

	@Column(name = "VAL_BUD_TRANS", nullable = false, precision = 22, scale = 0)
	public double getValBudTrans() {
		return this.valBudTrans;
	}

	public void setValBudTrans(double valBudTrans) {
		this.valBudTrans = valBudTrans;
	}

	@Column(name = "REF_VAL_BUD_TRANS", nullable = false, length = 30)
	public String getRefValBudTrans() {
		return this.refValBudTrans;
	}

	public void setRefValBudTrans(String refValBudTrans) {
		this.refValBudTrans = refValBudTrans;
	}

	@Column(name = "AREF_VAL_BUD_TRANS", nullable = false, length = 60)
	public String getArefValBudTrans() {
		return this.arefValBudTrans;
	}

	public void setArefValBudTrans(String arefValBudTrans) {
		this.arefValBudTrans = arefValBudTrans;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_VALEURS", length = 10)
	public Date getDateValeurs() {
		return this.dateValeurs;
	}

	public void setDateValeurs(Date dateValeurs) {
		this.dateValeurs = dateValeurs;
	}

}
