package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AvoirBudproj generated by hbm2java
 */
@Entity
@Table(name = "avoir_budproj", catalog = "ministere")
public class AvoirBudproj implements java.io.Serializable {

	private AvoirBudprojId id;
	private Projet projet;
	private DateAvoirBudproj dateAvoirBudproj;
	private double montant;
	private String reference;
	private String areference;
	private Date dateMontant;

	public AvoirBudproj() {
	}

	public AvoirBudproj(AvoirBudprojId id, Projet projet,
			DateAvoirBudproj dateAvoirBudproj, double montant,
			String reference, String areference) {
		this.id = id;
		this.projet = projet;
		this.dateAvoirBudproj = dateAvoirBudproj;
		this.montant = montant;
		this.reference = reference;
		this.areference = areference;
	}

	public AvoirBudproj(AvoirBudprojId id, Projet projet,
			DateAvoirBudproj dateAvoirBudproj, double montant,
			String reference, String areference, Date dateMontant) {
		this.id = id;
		this.projet = projet;
		this.dateAvoirBudproj = dateAvoirBudproj;
		this.montant = montant;
		this.reference = reference;
		this.areference = areference;
		this.dateMontant = dateMontant;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codeProj", column = @Column(name = "CODE_PROJ", nullable = false, length = 2)),
			@AttributeOverride(name = "dateAvoirBudproj", column = @Column(name = "DATE_AVOIR_BUDPROJ", nullable = false, length = 10)),
			@AttributeOverride(name = "numeroOrdreBudProj", column = @Column(name = "NUMERO_ORDRE_BUD_PROJ", nullable = false)),
			@AttributeOverride(name = "codeUtil", column = @Column(name = "CODE_UTIL", nullable = false, length = 8)) })
	public AvoirBudprojId getId() {
		return this.id;
	}

	public void setId(AvoirBudprojId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PROJ", nullable = false, insertable = false, updatable = false)
	public Projet getProjet() {
		return this.projet;
	}

	public void setProjet(Projet projet) {
		this.projet = projet;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DATE_AVOIR_BUDPROJ", nullable = false, insertable = false, updatable = false)
	public DateAvoirBudproj getDateAvoirBudproj() {
		return this.dateAvoirBudproj;
	}

	public void setDateAvoirBudproj(DateAvoirBudproj dateAvoirBudproj) {
		this.dateAvoirBudproj = dateAvoirBudproj;
	}

	@Column(name = "MONTANT", nullable = false, precision = 22, scale = 0)
	public double getMontant() {
		return this.montant;
	}

	public void setMontant(double montant) {
		this.montant = montant;
	}

	@Column(name = "REFERENCE", nullable = false, length = 30)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "AREFERENCE", nullable = false, length = 60)
	public String getAreference() {
		return this.areference;
	}

	public void setAreference(String areference) {
		this.areference = areference;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MONTANT", length = 10)
	public Date getDateMontant() {
		return this.dateMontant;
	}

	public void setDateMontant(Date dateMontant) {
		this.dateMontant = dateMontant;
	}

}
