package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvoirBudprojId generated by hbm2java
 */
@Embeddable
public class AvoirBudprojId implements java.io.Serializable {

	private String codeProj;
	private Date dateAvoirBudproj;
	private int numeroOrdreBudProj;
	private String codeUtil;

	public AvoirBudprojId() {
	}

	public AvoirBudprojId(String codeProj, Date dateAvoirBudproj,
			int numeroOrdreBudProj, String codeUtil) {
		this.codeProj = codeProj;
		this.dateAvoirBudproj = dateAvoirBudproj;
		this.numeroOrdreBudProj = numeroOrdreBudProj;
		this.codeUtil = codeUtil;
	}

	@Column(name = "CODE_PROJ", nullable = false, length = 2)
	public String getCodeProj() {
		return this.codeProj;
	}

	public void setCodeProj(String codeProj) {
		this.codeProj = codeProj;
	}

	@Column(name = "DATE_AVOIR_BUDPROJ", nullable = false, length = 10)
	public Date getDateAvoirBudproj() {
		return this.dateAvoirBudproj;
	}

	public void setDateAvoirBudproj(Date dateAvoirBudproj) {
		this.dateAvoirBudproj = dateAvoirBudproj;
	}

	@Column(name = "NUMERO_ORDRE_BUD_PROJ", nullable = false)
	public int getNumeroOrdreBudProj() {
		return this.numeroOrdreBudProj;
	}

	public void setNumeroOrdreBudProj(int numeroOrdreBudProj) {
		this.numeroOrdreBudProj = numeroOrdreBudProj;
	}

	@Column(name = "CODE_UTIL", nullable = false, length = 8)
	public String getCodeUtil() {
		return this.codeUtil;
	}

	public void setCodeUtil(String codeUtil) {
		this.codeUtil = codeUtil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvoirBudprojId))
			return false;
		AvoirBudprojId castOther = (AvoirBudprojId) other;

		return ((this.getCodeProj() == castOther.getCodeProj()) || (this
				.getCodeProj() != null && castOther.getCodeProj() != null && this
				.getCodeProj().equals(castOther.getCodeProj())))
				&& ((this.getDateAvoirBudproj() == castOther
						.getDateAvoirBudproj()) || (this.getDateAvoirBudproj() != null
						&& castOther.getDateAvoirBudproj() != null && this
						.getDateAvoirBudproj().equals(
								castOther.getDateAvoirBudproj())))
				&& (this.getNumeroOrdreBudProj() == castOther
						.getNumeroOrdreBudProj())
				&& ((this.getCodeUtil() == castOther.getCodeUtil()) || (this
						.getCodeUtil() != null
						&& castOther.getCodeUtil() != null && this
						.getCodeUtil().equals(castOther.getCodeUtil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodeProj() == null ? 0 : this.getCodeProj().hashCode());
		result = 37
				* result
				+ (getDateAvoirBudproj() == null ? 0 : this
						.getDateAvoirBudproj().hashCode());
		result = 37 * result + this.getNumeroOrdreBudProj();
		result = 37 * result
				+ (getCodeUtil() == null ? 0 : this.getCodeUtil().hashCode());
		return result;
	}

}
