package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AvoirBudorgId generated by hbm2java
 */
@Embeddable
public class AvoirBudorgId implements java.io.Serializable {

	private String codeOrg;
	private int annee;
	private int numeroOrdreBudOrg;
	private String codeUtil;
	

	public AvoirBudorgId() {
	}

	public AvoirBudorgId(String codeOrg, int annee, int numeroOrdreBudOrg,
			String codeUtil) {
		this.codeOrg = codeOrg;
		this.annee = annee;
		this.numeroOrdreBudOrg = numeroOrdreBudOrg;
		this.codeUtil = codeUtil;
	}

	@Column(name = "CODE_ORG", nullable = false, length = 6)
	public String getCodeOrg() {
		return this.codeOrg;
	}

	public void setCodeOrg(String codeOrg) {
		this.codeOrg = codeOrg;
	}

	@Column(name = "ANNEE", nullable = false)
	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	@Column(name = "NUMERO_ORDRE_BUD_ORG", nullable = false)
	public int getNumeroOrdreBudOrg() {
		return this.numeroOrdreBudOrg;
	}

	public void setNumeroOrdreBudOrg(int numeroOrdreBudOrg) {
		this.numeroOrdreBudOrg = numeroOrdreBudOrg;
	}

	@Column(name = "CODE_UTIL", nullable = false, length = 8)
	public String getCodeUtil() {
		return this.codeUtil;
	}

	public void setCodeUtil(String codeUtil) {
		this.codeUtil = codeUtil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AvoirBudorgId))
			return false;
		AvoirBudorgId castOther = (AvoirBudorgId) other;

		return ((this.getCodeOrg() == castOther.getCodeOrg()) || (this
				.getCodeOrg() != null && castOther.getCodeOrg() != null && this
				.getCodeOrg().equals(castOther.getCodeOrg())))
				&& (this.getAnnee() == castOther.getAnnee())
				&& (this.getNumeroOrdreBudOrg() == castOther
						.getNumeroOrdreBudOrg())
				&& ((this.getCodeUtil() == castOther.getCodeUtil()) || (this
						.getCodeUtil() != null
						&& castOther.getCodeUtil() != null && this
						.getCodeUtil().equals(castOther.getCodeUtil())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodeOrg() == null ? 0 : this.getCodeOrg().hashCode());
		result = 37 * result + this.getAnnee();
		result = 37 * result + this.getNumeroOrdreBudOrg();
		result = 37 * result
				+ (getCodeUtil() == null ? 0 : this.getCodeUtil().hashCode());
		return result;
	}

}
