package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "ministere")
public class Categorie implements java.io.Serializable {

	private String codeCategorie;
	private Organisme organisme;
	private String libelleCategorie;
	private String alibelleCategorie;
	private Set<Missionnaire> missionnaires = new HashSet<Missionnaire>(0);

	public Categorie() {
	}

	public Categorie(String codeCategorie) {
		this.codeCategorie = codeCategorie;
	}

	public Categorie(String codeCategorie, Organisme organisme,
			String libelleCategorie, String alibelleCategorie,
			Set<Missionnaire> missionnaires) {
		this.codeCategorie = codeCategorie;
		this.organisme = organisme;
		this.libelleCategorie = libelleCategorie;
		this.alibelleCategorie = alibelleCategorie;
		this.missionnaires = missionnaires;
	}

	@Id
	@Column(name = "CODE_CATEGORIE", unique = true, nullable = false, length = 2)
	public String getCodeCategorie() {
		return this.codeCategorie;
	}

	public void setCodeCategorie(String codeCategorie) {
		this.codeCategorie = codeCategorie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ORG")
	public Organisme getOrganisme() {
		return this.organisme;
	}

	public void setOrganisme(Organisme organisme) {
		this.organisme = organisme;
	}

	@Column(name = "LIBELLE_CATEGORIE", length = 60)
	public String getLibelleCategorie() {
		return this.libelleCategorie;
	}

	public void setLibelleCategorie(String libelleCategorie) {
		this.libelleCategorie = libelleCategorie;
	}

	@Column(name = "ALIBELLE_CATEGORIE", length = 120)
	public String getAlibelleCategorie() {
		return this.alibelleCategorie;
	}

	public void setAlibelleCategorie(String alibelleCategorie) {
		this.alibelleCategorie = alibelleCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Missionnaire> getMissionnaires() {
		return this.missionnaires;
	}

	public void setMissionnaires(Set<Missionnaire> missionnaires) {
		this.missionnaires = missionnaires;
	}

}
