package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EtatMission generated by hbm2java
 */
@Entity
@Table(name = "etat_mission", catalog = "ministere")
public class EtatMission implements java.io.Serializable {

	private String codeEtatMission;
	private String libelleEtatMission;
	private String alibelleEtatMission;

	public EtatMission() {
	}

	public EtatMission(String codeEtatMission) {
		this.codeEtatMission = codeEtatMission;
	}

	public EtatMission(String codeEtatMission, String libelleEtatMission,
			String alibelleEtatMission) {
		this.codeEtatMission = codeEtatMission;
		this.libelleEtatMission = libelleEtatMission;
		this.alibelleEtatMission = alibelleEtatMission;
	}

	@Id
	@Column(name = "CODE_ETAT_MISSION", unique = true, nullable = false, length = 2)
	public String getCodeEtatMission() {
		return this.codeEtatMission;
	}

	public void setCodeEtatMission(String codeEtatMission) {
		this.codeEtatMission = codeEtatMission;
	}

	@Column(name = "LIBELLE_ETAT_MISSION", length = 100)
	public String getLibelleEtatMission() {
		return this.libelleEtatMission;
	}

	public void setLibelleEtatMission(String libelleEtatMission) {
		this.libelleEtatMission = libelleEtatMission;
	}

	@Column(name = "ALIBELLE_ETAT_MISSION", length = 200)
	public String getAlibelleEtatMission() {
		return this.alibelleEtatMission;
	}

	public void setAlibelleEtatMission(String alibelleEtatMission) {
		this.alibelleEtatMission = alibelleEtatMission;
	}

}
