package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "ministere")
public class Grade implements java.io.Serializable {

	private String codeGrade;
	private Organisme organisme;
	private String libelleGrade;
	private String alibelleGrade;
	private Set<Missionnaire> missionnaires = new HashSet<Missionnaire>(0);

	public Grade() {
	}

	public Grade(String codeGrade) {
		this.codeGrade = codeGrade;
	}

	public Grade(String codeGrade, Organisme organisme, String libelleGrade,
			String alibelleGrade, Set<Missionnaire> missionnaires) {
		this.codeGrade = codeGrade;
		this.organisme = organisme;
		this.libelleGrade = libelleGrade;
		this.alibelleGrade = alibelleGrade;
		this.missionnaires = missionnaires;
	}

	@Id
	@Column(name = "CODE_GRADE", unique = true, nullable = false, length = 2)
	public String getCodeGrade() {
		return this.codeGrade;
	}

	public void setCodeGrade(String codeGrade) {
		this.codeGrade = codeGrade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ORG")
	public Organisme getOrganisme() {
		return this.organisme;
	}

	public void setOrganisme(Organisme organisme) {
		this.organisme = organisme;
	}

	@Column(name = "LIBELLE_GRADE", length = 60)
	public String getLibelleGrade() {
		return this.libelleGrade;
	}

	public void setLibelleGrade(String libelleGrade) {
		this.libelleGrade = libelleGrade;
	}

	@Column(name = "ALIBELLE_GRADE", length = 120)
	public String getAlibelleGrade() {
		return this.alibelleGrade;
	}

	public void setAlibelleGrade(String alibelleGrade) {
		this.alibelleGrade = alibelleGrade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Missionnaire> getMissionnaires() {
		return this.missionnaires;
	}

	public void setMissionnaires(Set<Missionnaire> missionnaires) {
		this.missionnaires = missionnaires;
	}

}
