package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupe", catalog = "ministere")
public class Groupe implements java.io.Serializable {

	private String codeGroupe;
	private String libelleGroupe;
	private String alibelleGroupe;
	private Set<Missionnaire> missionnaires = new HashSet<Missionnaire>(0);

	public Groupe() {
	}

	public Groupe(String codeGroupe) {
		this.codeGroupe = codeGroupe;
	}

	public Groupe(String codeGroupe, String libelleGroupe,
			String alibelleGroupe, Set<Missionnaire> missionnaires) {
		this.codeGroupe = codeGroupe;
		this.libelleGroupe = libelleGroupe;
		this.alibelleGroupe = alibelleGroupe;
		this.missionnaires = missionnaires;
	}

	@Id
	@Column(name = "CODE_GROUPE", unique = true, nullable = false, length = 1)
	public String getCodeGroupe() {
		return this.codeGroupe;
	}

	public void setCodeGroupe(String codeGroupe) {
		this.codeGroupe = codeGroupe;
	}

	@Column(name = "LIBELLE_GROUPE", length = 60)
	public String getLibelleGroupe() {
		return this.libelleGroupe;
	}

	public void setLibelleGroupe(String libelleGroupe) {
		this.libelleGroupe = libelleGroupe;
	}

	@Column(name = "ALIBELLE_GROUPE", length = 120)
	public String getAlibelleGroupe() {
		return this.alibelleGroupe;
	}

	public void setAlibelleGroupe(String alibelleGroupe) {
		this.alibelleGroupe = alibelleGroupe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupe")
	public Set<Missionnaire> getMissionnaires() {
		return this.missionnaires;
	}

	public void setMissionnaires(Set<Missionnaire> missionnaires) {
		this.missionnaires = missionnaires;
	}

}
