package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Missionnaire generated by hbm2java
 */
@Entity
@Table(name = "missionnaire", catalog = "ministere")
public class Missionnaire implements java.io.Serializable {

	private String cinMissionnaire;
	private Groupe groupe;
	private Categorie categorie;
	private Grade grade;
	private Fonction fonction;
	private String matriculeMissionnaire;
	private String nomMissionnaire;
	private String anomMissionnaire;
	private String prenomMissionnaire;
	private String aprenomMissionnaire;
	private String nationaliteMissionnaire;
	private String anationaliteMissionnaire;
	private Date dateNaisMissionnaire;
	private String lieuNaisMissionnaire;
	private String alieuNaisMissionnaire;
	private Date dateLivCinMissionnaire;
	private String lieuLivCinMissionnaire;
	private String alieuLivrCinMissionnaire;
	private String niveauSalaireMissionnaire;
	private Integer telephoneMissionnaire;

	public Missionnaire() {
	}

	public Missionnaire(String cinMissionnaire, Groupe groupe,
			Categorie categorie, Grade grade, Fonction fonction) {
		this.cinMissionnaire = cinMissionnaire;
		this.groupe = groupe;
		this.categorie = categorie;
		this.grade = grade;
		this.fonction = fonction;
	}

	public Missionnaire(String cinMissionnaire, Groupe groupe,
			Categorie categorie, Grade grade, Fonction fonction,
			String matriculeMissionnaire, String nomMissionnaire,
			String anomMissionnaire, String prenomMissionnaire,
			String aprenomMissionnaire, String nationaliteMissionnaire,
			String anationaliteMissionnaire, Date dateNaisMissionnaire,
			String lieuNaisMissionnaire, String alieuNaisMissionnaire,
			Date dateLivCinMissionnaire, String lieuLivCinMissionnaire,
			String alieuLivrCinMissionnaire, String niveauSalaireMissionnaire,
			Integer telephoneMissionnaire) {
		this.cinMissionnaire = cinMissionnaire;
		this.groupe = groupe;
		this.categorie = categorie;
		this.grade = grade;
		this.fonction = fonction;
		this.matriculeMissionnaire = matriculeMissionnaire;
		this.nomMissionnaire = nomMissionnaire;
		this.anomMissionnaire = anomMissionnaire;
		this.prenomMissionnaire = prenomMissionnaire;
		this.aprenomMissionnaire = aprenomMissionnaire;
		this.nationaliteMissionnaire = nationaliteMissionnaire;
		this.anationaliteMissionnaire = anationaliteMissionnaire;
		this.dateNaisMissionnaire = dateNaisMissionnaire;
		this.lieuNaisMissionnaire = lieuNaisMissionnaire;
		this.alieuNaisMissionnaire = alieuNaisMissionnaire;
		this.dateLivCinMissionnaire = dateLivCinMissionnaire;
		this.lieuLivCinMissionnaire = lieuLivCinMissionnaire;
		this.alieuLivrCinMissionnaire = alieuLivrCinMissionnaire;
		this.niveauSalaireMissionnaire = niveauSalaireMissionnaire;
		this.telephoneMissionnaire = telephoneMissionnaire;
	}

	@Id
	@Column(name = "CIN_MISSIONNAIRE", unique = true, nullable = false, length = 10)
	public String getCinMissionnaire() {
		return this.cinMissionnaire;
	}

	public void setCinMissionnaire(String cinMissionnaire) {
		this.cinMissionnaire = cinMissionnaire;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_GROUPE", nullable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_CATEGORIE", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_GRADE", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_FONCTION", nullable = false)
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@Column(name = "MATRICULE_MISSIONNAIRE", length = 10)
	public String getMatriculeMissionnaire() {
		return this.matriculeMissionnaire;
	}

	public void setMatriculeMissionnaire(String matriculeMissionnaire) {
		this.matriculeMissionnaire = matriculeMissionnaire;
	}

	@Column(name = "NOM_MISSIONNAIRE", length = 20)
	public String getNomMissionnaire() {
		return this.nomMissionnaire;
	}

	public void setNomMissionnaire(String nomMissionnaire) {
		this.nomMissionnaire = nomMissionnaire;
	}

	@Column(name = "ANOM_MISSIONNAIRE", length = 40)
	public String getAnomMissionnaire() {
		return this.anomMissionnaire;
	}

	public void setAnomMissionnaire(String anomMissionnaire) {
		this.anomMissionnaire = anomMissionnaire;
	}

	@Column(name = "PRENOM_MISSIONNAIRE", length = 20)
	public String getPrenomMissionnaire() {
		return this.prenomMissionnaire;
	}

	public void setPrenomMissionnaire(String prenomMissionnaire) {
		this.prenomMissionnaire = prenomMissionnaire;
	}

	@Column(name = "APRENOM_MISSIONNAIRE", length = 40)
	public String getAprenomMissionnaire() {
		return this.aprenomMissionnaire;
	}

	public void setAprenomMissionnaire(String aprenomMissionnaire) {
		this.aprenomMissionnaire = aprenomMissionnaire;
	}

	@Column(name = "NATIONALITE_MISSIONNAIRE", length = 20)
	public String getNationaliteMissionnaire() {
		return this.nationaliteMissionnaire;
	}

	public void setNationaliteMissionnaire(String nationaliteMissionnaire) {
		this.nationaliteMissionnaire = nationaliteMissionnaire;
	}

	@Column(name = "ANATIONALITE_MISSIONNAIRE", length = 40)
	public String getAnationaliteMissionnaire() {
		return this.anationaliteMissionnaire;
	}

	public void setAnationaliteMissionnaire(String anationaliteMissionnaire) {
		this.anationaliteMissionnaire = anationaliteMissionnaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAIS_MISSIONNAIRE", length = 10)
	public Date getDateNaisMissionnaire() {
		return this.dateNaisMissionnaire;
	}

	public void setDateNaisMissionnaire(Date dateNaisMissionnaire) {
		this.dateNaisMissionnaire = dateNaisMissionnaire;
	}

	@Column(name = "LIEU_NAIS_MISSIONNAIRE", length = 40)
	public String getLieuNaisMissionnaire() {
		return this.lieuNaisMissionnaire;
	}

	public void setLieuNaisMissionnaire(String lieuNaisMissionnaire) {
		this.lieuNaisMissionnaire = lieuNaisMissionnaire;
	}

	@Column(name = "ALIEU_NAIS_MISSIONNAIRE", length = 80)
	public String getAlieuNaisMissionnaire() {
		return this.alieuNaisMissionnaire;
	}

	public void setAlieuNaisMissionnaire(String alieuNaisMissionnaire) {
		this.alieuNaisMissionnaire = alieuNaisMissionnaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_LIV_CIN_MISSIONNAIRE", length = 10)
	public Date getDateLivCinMissionnaire() {
		return this.dateLivCinMissionnaire;
	}

	public void setDateLivCinMissionnaire(Date dateLivCinMissionnaire) {
		this.dateLivCinMissionnaire = dateLivCinMissionnaire;
	}

	@Column(name = "LIEU_LIV_CIN_MISSIONNAIRE", length = 40)
	public String getLieuLivCinMissionnaire() {
		return this.lieuLivCinMissionnaire;
	}

	public void setLieuLivCinMissionnaire(String lieuLivCinMissionnaire) {
		this.lieuLivCinMissionnaire = lieuLivCinMissionnaire;
	}

	@Column(name = "ALIEU_LIVR_CIN_MISSIONNAIRE", length = 80)
	public String getAlieuLivrCinMissionnaire() {
		return this.alieuLivrCinMissionnaire;
	}

	public void setAlieuLivrCinMissionnaire(String alieuLivrCinMissionnaire) {
		this.alieuLivrCinMissionnaire = alieuLivrCinMissionnaire;
	}

	@Column(name = "NIVEAU_SALAIRE_MISSIONNAIRE", length = 3)
	public String getNiveauSalaireMissionnaire() {
		return this.niveauSalaireMissionnaire;
	}

	public void setNiveauSalaireMissionnaire(String niveauSalaireMissionnaire) {
		this.niveauSalaireMissionnaire = niveauSalaireMissionnaire;
	}

	@Column(name = "TELEPHONE_MISSIONNAIRE")
	public Integer getTelephoneMissionnaire() {
		return this.telephoneMissionnaire;
	}

	public void setTelephoneMissionnaire(Integer telephoneMissionnaire) {
		this.telephoneMissionnaire = telephoneMissionnaire;
	}

}
