package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MoyenTransport generated by hbm2java
 */
@Entity
@Table(name = "moyen_transport", catalog = "ministere")
public class MoyenTransport implements java.io.Serializable {

	private String codeMoyenDeTransport;
	private String libelleMoyenDeTransport;
	private String alibelleMoyenDeTransport;

	public MoyenTransport() {
	}

	public MoyenTransport(String codeMoyenDeTransport) {
		this.codeMoyenDeTransport = codeMoyenDeTransport;
	}

	public MoyenTransport(String codeMoyenDeTransport,
			String libelleMoyenDeTransport, String alibelleMoyenDeTransport) {
		this.codeMoyenDeTransport = codeMoyenDeTransport;
		this.libelleMoyenDeTransport = libelleMoyenDeTransport;
		this.alibelleMoyenDeTransport = alibelleMoyenDeTransport;
	}

	@Id
	@Column(name = "CODE_MOYEN_DE_TRANSPORT", unique = true, nullable = false, length = 3)
	public String getCodeMoyenDeTransport() {
		return this.codeMoyenDeTransport;
	}

	public void setCodeMoyenDeTransport(String codeMoyenDeTransport) {
		this.codeMoyenDeTransport = codeMoyenDeTransport;
	}

	@Column(name = "LIBELLE_MOYEN_DE_TRANSPORT", length = 20)
	public String getLibelleMoyenDeTransport() {
		return this.libelleMoyenDeTransport;
	}

	public void setLibelleMoyenDeTransport(String libelleMoyenDeTransport) {
		this.libelleMoyenDeTransport = libelleMoyenDeTransport;
	}

	@Column(name = "ALIBELLE_MOYEN_DE_TRANSPORT", length = 40)
	public String getAlibelleMoyenDeTransport() {
		return this.alibelleMoyenDeTransport;
	}

	public void setAlibelleMoyenDeTransport(String alibelleMoyenDeTransport) {
		this.alibelleMoyenDeTransport = alibelleMoyenDeTransport;
	}

}
