package tn.ministere.entity;

// Generated 26 mai 2014 15:44:48 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdreMissionId generated by hbm2java
 */
@Embeddable
public class OrdreMissionId implements java.io.Serializable {

	private String numMission;
	private String codeMoyenDeTransport;
	private String cinMissionnaire;
	private String typeFrais;
	private String codeVilleDestination;
	private String codeEtatMission;
	private int numOrdreMission;

	public OrdreMissionId() {
	}

	public OrdreMissionId(String numMission, String codeMoyenDeTransport,
			String cinMissionnaire, String typeFrais,
			String codeVilleDestination, String codeEtatMission,
			int numOrdreMission) {
		this.numMission = numMission;
		this.codeMoyenDeTransport = codeMoyenDeTransport;
		this.cinMissionnaire = cinMissionnaire;
		this.typeFrais = typeFrais;
		this.codeVilleDestination = codeVilleDestination;
		this.codeEtatMission = codeEtatMission;
		this.numOrdreMission = numOrdreMission;
	}

	@Column(name = "NUM_MISSION", nullable = false, length = 6)
	public String getNumMission() {
		return this.numMission;
	}

	public void setNumMission(String numMission) {
		this.numMission = numMission;
	}

	@Column(name = "CODE_MOYEN_DE_TRANSPORT", nullable = false, length = 3)
	public String getCodeMoyenDeTransport() {
		return this.codeMoyenDeTransport;
	}

	public void setCodeMoyenDeTransport(String codeMoyenDeTransport) {
		this.codeMoyenDeTransport = codeMoyenDeTransport;
	}

	@Column(name = "CIN_MISSIONNAIRE", nullable = false, length = 10)
	public String getCinMissionnaire() {
		return this.cinMissionnaire;
	}

	public void setCinMissionnaire(String cinMissionnaire) {
		this.cinMissionnaire = cinMissionnaire;
	}

	@Column(name = "TYPE_FRAIS", nullable = false, length = 1)
	public String getTypeFrais() {
		return this.typeFrais;
	}

	public void setTypeFrais(String typeFrais) {
		this.typeFrais = typeFrais;
	}

	@Column(name = "CODE_VILLE_DESTINATION", nullable = false, length = 2)
	public String getCodeVilleDestination() {
		return this.codeVilleDestination;
	}

	public void setCodeVilleDestination(String codeVilleDestination) {
		this.codeVilleDestination = codeVilleDestination;
	}

	@Column(name = "CODE_ETAT_MISSION", nullable = false, length = 1)
	public String getCodeEtatMission() {
		return this.codeEtatMission;
	}

	public void setCodeEtatMission(String codeEtatMission) {
		this.codeEtatMission = codeEtatMission;
	}

	@Column(name = "NUM_ORDRE_MISSION", nullable = false)
	public int getNumOrdreMission() {
		return this.numOrdreMission;
	}

	public void setNumOrdreMission(int numOrdreMission) {
		this.numOrdreMission = numOrdreMission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdreMissionId))
			return false;
		OrdreMissionId castOther = (OrdreMissionId) other;

		return ((this.getNumMission() == castOther.getNumMission()) || (this
				.getNumMission() != null && castOther.getNumMission() != null && this
				.getNumMission().equals(castOther.getNumMission())))
				&& ((this.getCodeMoyenDeTransport() == castOther
						.getCodeMoyenDeTransport()) || (this
						.getCodeMoyenDeTransport() != null
						&& castOther.getCodeMoyenDeTransport() != null && this
						.getCodeMoyenDeTransport().equals(
								castOther.getCodeMoyenDeTransport())))
				&& ((this.getCinMissionnaire() == castOther
						.getCinMissionnaire()) || (this.getCinMissionnaire() != null
						&& castOther.getCinMissionnaire() != null && this
						.getCinMissionnaire().equals(
								castOther.getCinMissionnaire())))
				&& ((this.getTypeFrais() == castOther.getTypeFrais()) || (this
						.getTypeFrais() != null
						&& castOther.getTypeFrais() != null && this
						.getTypeFrais().equals(castOther.getTypeFrais())))
				&& ((this.getCodeVilleDestination() == castOther
						.getCodeVilleDestination()) || (this
						.getCodeVilleDestination() != null
						&& castOther.getCodeVilleDestination() != null && this
						.getCodeVilleDestination().equals(
								castOther.getCodeVilleDestination())))
				&& ((this.getCodeEtatMission() == castOther
						.getCodeEtatMission()) || (this.getCodeEtatMission() != null
						&& castOther.getCodeEtatMission() != null && this
						.getCodeEtatMission().equals(
								castOther.getCodeEtatMission())))
				&& (this.getNumOrdreMission() == castOther.getNumOrdreMission());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumMission() == null ? 0 : this.getNumMission()
						.hashCode());
		result = 37
				* result
				+ (getCodeMoyenDeTransport() == null ? 0 : this
						.getCodeMoyenDeTransport().hashCode());
		result = 37
				* result
				+ (getCinMissionnaire() == null ? 0 : this.getCinMissionnaire()
						.hashCode());
		result = 37 * result
				+ (getTypeFrais() == null ? 0 : this.getTypeFrais().hashCode());
		result = 37
				* result
				+ (getCodeVilleDestination() == null ? 0 : this
						.getCodeVilleDestination().hashCode());
		result = 37
				* result
				+ (getCodeEtatMission() == null ? 0 : this.getCodeEtatMission()
						.hashCode());
		result = 37 * result + this.getNumOrdreMission();
		return result;
	}

}
