package tn.ministere.entity;

// Generated 26 mai 2014 15:44:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdreMission generated by hbm2java
 */
@Entity
@Table(name = "ordre_mission", catalog = "ministere")
public class OrdreMission implements java.io.Serializable {

	private OrdreMissionId id;
	private Date dateDepProMissionnaire;
	private Date dateArProMissionnaire;
	private Date dateDepReMissionnaire;
	private Date dateArReMissionnaire;
	private double montantPrevisionnel;
	private Double montantReel;
	private String montantSupprteParQui;
	private String amontantSupprteParQui;
	private String supporteCode;
	private Double avanceAccompte;
	private Integer numBpayement;
	private Date dateBpayement;
	private Double avanceAccepte;
	private Integer numOrdrePayement;
	private Date dateOpayement;
	private String codeOrg;
	private String codeTheme;

	public OrdreMission() {
	}

	public OrdreMission(OrdreMissionId id, double montantPrevisionnel,
			String montantSupprteParQui, String amontantSupprteParQui,
			String supporteCode) {
		this.id = id;
		this.montantPrevisionnel = montantPrevisionnel;
		this.montantSupprteParQui = montantSupprteParQui;
		this.amontantSupprteParQui = amontantSupprteParQui;
		this.supporteCode = supporteCode;
	}

	public OrdreMission(OrdreMissionId id, Date dateDepProMissionnaire,
			Date dateArProMissionnaire, Date dateDepReMissionnaire,
			Date dateArReMissionnaire, double montantPrevisionnel,
			Double montantReel, String montantSupprteParQui,
			String amontantSupprteParQui, String supporteCode,
			Double avanceAccompte, Integer numBpayement, Date dateBpayement,
			Double avanceAccepte, Integer numOrdrePayement, Date dateOpayement,
			String codeOrg, String codeTheme) {
		this.id = id;
		this.dateDepProMissionnaire = dateDepProMissionnaire;
		this.dateArProMissionnaire = dateArProMissionnaire;
		this.dateDepReMissionnaire = dateDepReMissionnaire;
		this.dateArReMissionnaire = dateArReMissionnaire;
		this.montantPrevisionnel = montantPrevisionnel;
		this.montantReel = montantReel;
		this.montantSupprteParQui = montantSupprteParQui;
		this.amontantSupprteParQui = amontantSupprteParQui;
		this.supporteCode = supporteCode;
		this.avanceAccompte = avanceAccompte;
		this.numBpayement = numBpayement;
		this.dateBpayement = dateBpayement;
		this.avanceAccepte = avanceAccepte;
		this.numOrdrePayement = numOrdrePayement;
		this.dateOpayement = dateOpayement;
		this.codeOrg = codeOrg;
		this.codeTheme = codeTheme;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numMission", column = @Column(name = "NUM_MISSION", nullable = false, length = 6)),
			@AttributeOverride(name = "codeMoyenDeTransport", column = @Column(name = "CODE_MOYEN_DE_TRANSPORT", nullable = false, length = 3)),
			@AttributeOverride(name = "cinMissionnaire", column = @Column(name = "CIN_MISSIONNAIRE", nullable = false, length = 10)),
			@AttributeOverride(name = "typeFrais", column = @Column(name = "TYPE_FRAIS", nullable = false, length = 1)),
			@AttributeOverride(name = "codeVilleDestination", column = @Column(name = "CODE_VILLE_DESTINATION", nullable = false, length = 2)),
			@AttributeOverride(name = "codeEtatMission", column = @Column(name = "CODE_ETAT_MISSION", nullable = false, length = 1)),
			@AttributeOverride(name = "numOrdreMission", column = @Column(name = "NUM_ORDRE_MISSION", nullable = false)) })
	public OrdreMissionId getId() {
		return this.id;
	}

	public void setId(OrdreMissionId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEP_PRO_MISSIONNAIRE", length = 10)
	public Date getDateDepProMissionnaire() {
		return this.dateDepProMissionnaire;
	}

	public void setDateDepProMissionnaire(Date dateDepProMissionnaire) {
		this.dateDepProMissionnaire = dateDepProMissionnaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_AR_PRO_MISSIONNAIRE", length = 10)
	public Date getDateArProMissionnaire() {
		return this.dateArProMissionnaire;
	}

	public void setDateArProMissionnaire(Date dateArProMissionnaire) {
		this.dateArProMissionnaire = dateArProMissionnaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEP_RE_MISSIONNAIRE", length = 10)
	public Date getDateDepReMissionnaire() {
		return this.dateDepReMissionnaire;
	}

	public void setDateDepReMissionnaire(Date dateDepReMissionnaire) {
		this.dateDepReMissionnaire = dateDepReMissionnaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_AR_RE_MISSIONNAIRE", length = 10)
	public Date getDateArReMissionnaire() {
		return this.dateArReMissionnaire;
	}

	public void setDateArReMissionnaire(Date dateArReMissionnaire) {
		this.dateArReMissionnaire = dateArReMissionnaire;
	}

	@Column(name = "MONTANT_PREVISIONNEL", nullable = false, precision = 22, scale = 0)
	public double getMontantPrevisionnel() {
		return this.montantPrevisionnel;
	}

	public void setMontantPrevisionnel(double montantPrevisionnel) {
		this.montantPrevisionnel = montantPrevisionnel;
	}

	@Column(name = "MONTANT_REEL", precision = 22, scale = 0)
	public Double getMontantReel() {
		return this.montantReel;
	}

	public void setMontantReel(Double montantReel) {
		this.montantReel = montantReel;
	}

	@Column(name = "MONTANT_SUPPRTE_PAR_QUI", nullable = false, length = 30)
	public String getMontantSupprteParQui() {
		return this.montantSupprteParQui;
	}

	public void setMontantSupprteParQui(String montantSupprteParQui) {
		this.montantSupprteParQui = montantSupprteParQui;
	}

	@Column(name = "AMONTANT_SUPPRTE_PAR_QUI", nullable = false, length = 60)
	public String getAmontantSupprteParQui() {
		return this.amontantSupprteParQui;
	}

	public void setAmontantSupprteParQui(String amontantSupprteParQui) {
		this.amontantSupprteParQui = amontantSupprteParQui;
	}

	@Column(name = "SUPPORTE_CODE", nullable = false, length = 1)
	public String getSupporteCode() {
		return this.supporteCode;
	}

	public void setSupporteCode(String supporteCode) {
		this.supporteCode = supporteCode;
	}

	@Column(name = "AVANCE_ACCOMPTE", precision = 22, scale = 0)
	public Double getAvanceAccompte() {
		return this.avanceAccompte;
	}

	public void setAvanceAccompte(Double avanceAccompte) {
		this.avanceAccompte = avanceAccompte;
	}

	@Column(name = "NUM_BPAYEMENT")
	public Integer getNumBpayement() {
		return this.numBpayement;
	}

	public void setNumBpayement(Integer numBpayement) {
		this.numBpayement = numBpayement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_BPAYEMENT", length = 10)
	public Date getDateBpayement() {
		return this.dateBpayement;
	}

	public void setDateBpayement(Date dateBpayement) {
		this.dateBpayement = dateBpayement;
	}

	@Column(name = "AVANCE_ACCEPTE", precision = 22, scale = 0)
	public Double getAvanceAccepte() {
		return this.avanceAccepte;
	}

	public void setAvanceAccepte(Double avanceAccepte) {
		this.avanceAccepte = avanceAccepte;
	}

	@Column(name = "NUM_ORDRE_PAYEMENT")
	public Integer getNumOrdrePayement() {
		return this.numOrdrePayement;
	}

	public void setNumOrdrePayement(Integer numOrdrePayement) {
		this.numOrdrePayement = numOrdrePayement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OPAYEMENT", length = 10)
	public Date getDateOpayement() {
		return this.dateOpayement;
	}

	public void setDateOpayement(Date dateOpayement) {
		this.dateOpayement = dateOpayement;
	}

	@Column(name = "code_org", length = 6)
	public String getCodeOrg() {
		return this.codeOrg;
	}

	public void setCodeOrg(String codeOrg) {
		this.codeOrg = codeOrg;
	}

	@Column(name = "code_theme", length = 3)
	public String getCodeTheme() {
		return this.codeTheme;
	}

	public void setCodeTheme(String codeTheme) {
		this.codeTheme = codeTheme;
	}

}
