package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaysDestination generated by hbm2java
 */
@Entity
@Table(name = "pays_destination", catalog = "ministere")
public class PaysDestination implements java.io.Serializable {

	private String codePaysDes;
	private Zone zone;
	private String libellePaysDes;
	private String alibellePaysDes;
	private String langue;
	private Set<VilleDestination> villeDestinations = new HashSet<VilleDestination>(
			0);

	public PaysDestination() {
	}

	public PaysDestination(String codePaysDes, Zone zone) {
		this.codePaysDes = codePaysDes;
		this.zone = zone;
	}

	public PaysDestination(String codePaysDes, Zone zone,
			String libellePaysDes, String alibellePaysDes, String langue,
			Set<VilleDestination> villeDestinations) {
		this.codePaysDes = codePaysDes;
		this.zone = zone;
		this.libellePaysDes = libellePaysDes;
		this.alibellePaysDes = alibellePaysDes;
		this.langue = langue;
		this.villeDestinations = villeDestinations;
	}

	@Id
	@Column(name = "CODE_PAYS_DES", unique = true, nullable = false, length = 2)
	public String getCodePaysDes() {
		return this.codePaysDes;
	}

	public void setCodePaysDes(String codePaysDes) {
		this.codePaysDes = codePaysDes;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ZONE", nullable = false)
	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	@Column(name = "LIBELLE_PAYS_DES", length = 15)
	public String getLibellePaysDes() {
		return this.libellePaysDes;
	}

	public void setLibellePaysDes(String libellePaysDes) {
		this.libellePaysDes = libellePaysDes;
	}

	@Column(name = "ALIBELLE_PAYS_DES", length = 30)
	public String getAlibellePaysDes() {
		return this.alibellePaysDes;
	}

	public void setAlibellePaysDes(String alibellePaysDes) {
		this.alibellePaysDes = alibellePaysDes;
	}

	@Column(name = "LANGUE", length = 20)
	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paysDestination")
	public Set<VilleDestination> getVilleDestinations() {
		return this.villeDestinations;
	}

	public void setVilleDestinations(Set<VilleDestination> villeDestinations) {
		this.villeDestinations = villeDestinations;
	}

}
