package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", catalog = "ministere")
public class Profil implements java.io.Serializable {

	private String codeProfil;
	private String libelleProfil;
	private String alibelleProfil;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Profil() {
	}

	public Profil(String codeProfil) {
		this.codeProfil = codeProfil;
	}

	public Profil(String codeProfil, String libelleProfil,
			String alibelleProfil, Set<Utilisateur> utilisateurs) {
		this.codeProfil = codeProfil;
		this.libelleProfil = libelleProfil;
		this.alibelleProfil = alibelleProfil;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "CODE_PROFIL", unique = true, nullable = false, length = 6)
	public String getCodeProfil() {
		return this.codeProfil;
	}

	public void setCodeProfil(String codeProfil) {
		this.codeProfil = codeProfil;
	}

	@Column(name = "LIBELLE_PROFIL", length = 20)
	public String getLibelleProfil() {
		return this.libelleProfil;
	}

	public void setLibelleProfil(String libelleProfil) {
		this.libelleProfil = libelleProfil;
	}

	@Column(name = "ALIBELLE_PROFIL", length = 40)
	public String getAlibelleProfil() {
		return this.alibelleProfil;
	}

	public void setAlibelleProfil(String alibelleProfil) {
		this.alibelleProfil = alibelleProfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
