package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name = "projet", catalog = "ministere")
public class Projet implements java.io.Serializable {

	private String codeProj;
	private Organisme organisme;
	private String nomProj;
	private String anomProj;
	private List<AvoirBudproj> avoirBudprojs;

	public Projet() {
	}

	public Projet(String codeProj, Organisme organisme) {
		this.codeProj = codeProj;
		this.organisme = organisme;
	}

	public Projet(String codeProj, Organisme organisme, String nomProj,
			String anomProj, List<AvoirBudproj> avoirBudprojs) {
		this.codeProj = codeProj;
		this.organisme = organisme;
		this.nomProj = nomProj;
		this.anomProj = anomProj;
		this.avoirBudprojs = avoirBudprojs;
	}

	@Id
	@Column(name = "CODE_PROJ", unique = true, nullable = false, length = 2)
	public String getCodeProj() {
		return this.codeProj;
	}

	public void setCodeProj(String codeProj) {
		this.codeProj = codeProj;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ORG", nullable = false)
	public Organisme getOrganisme() {
		return this.organisme;
	}

	public void setOrganisme(Organisme organisme) {
		this.organisme = organisme;
	}

	@Column(name = "NOM_PROJ", length = 100)
	public String getNomProj() {
		return this.nomProj;
	}

	public void setNomProj(String nomProj) {
		this.nomProj = nomProj;
	}

	@Column(name = "ANOM_PROJ", length = 200)
	public String getAnomProj() {
		return this.anomProj;
	}

	public void setAnomProj(String anomProj) {
		this.anomProj = anomProj;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "projet")
	public List<AvoirBudproj> getAvoirBudprojs() {
		return this.avoirBudprojs;
	}

	public void setAvoirBudprojs(List<AvoirBudproj> avoirBudprojs) {
		this.avoirBudprojs = avoirBudprojs;
	}

}
