package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TauxPec generated by hbm2java
 */
@Entity
@Table(name = "taux_pec", catalog = "ministere")
public class TauxPec implements java.io.Serializable {

	private String codeTaux;
	private String libtaux;
	private String alibtaux;

	public TauxPec() {
	}

	public TauxPec(String codeTaux) {
		this.codeTaux = codeTaux;
	}

	public TauxPec(String codeTaux, String libtaux, String alibtaux) {
		this.codeTaux = codeTaux;
		this.libtaux = libtaux;
		this.alibtaux = alibtaux;
	}

	@Id
	@Column(name = "CODE_TAUX", unique = true, nullable = false, length = 2)
	public String getCodeTaux() {
		return this.codeTaux;
	}

	public void setCodeTaux(String codeTaux) {
		this.codeTaux = codeTaux;
	}

	@Column(name = "LIBTAUX", length = 20)
	public String getLibtaux() {
		return this.libtaux;
	}

	public void setLibtaux(String libtaux) {
		this.libtaux = libtaux;
	}

	@Column(name = "ALIBTAUX", length = 40)
	public String getAlibtaux() {
		return this.alibtaux;
	}

	public void setAlibtaux(String alibtaux) {
		this.alibtaux = alibtaux;
	}

}
