package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "theme", catalog = "ministere")
public class Theme implements java.io.Serializable {

	private String codeTheme;
	private String libelleTheme;
	private String alibelleTheme;
	private Set<Mission> missions = new HashSet<Mission>(0);

	public Theme() {
	}

	public Theme(String codeTheme) {
		this.codeTheme = codeTheme;
	}

	public Theme(String codeTheme, String libelleTheme, String alibelleTheme,
			Set<Mission> missions) {
		this.codeTheme = codeTheme;
		this.libelleTheme = libelleTheme;
		this.alibelleTheme = alibelleTheme;
		this.missions = missions;
	}

	@Id
	@Column(name = "CODE_THEME", unique = true, nullable = false, length = 3)
	public String getCodeTheme() {
		return this.codeTheme;
	}

	public void setCodeTheme(String codeTheme) {
		this.codeTheme = codeTheme;
	}

	@Column(name = "LIBELLE_THEME", length = 40)
	public String getLibelleTheme() {
		return this.libelleTheme;
	}

	public void setLibelleTheme(String libelleTheme) {
		this.libelleTheme = libelleTheme;
	}

	@Column(name = "ALIBELLE_THEME", length = 80)
	public String getAlibelleTheme() {
		return this.alibelleTheme;
	}

	public void setAlibelleTheme(String alibelleTheme) {
		this.alibelleTheme = alibelleTheme;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theme")
	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

}
