package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeFrais generated by hbm2java
 */
@Entity
@Table(name = "type_frais", catalog = "ministere")
public class TypeFrais implements java.io.Serializable {

	private String typeFrais;
	private String libelleFrais;
	private String alibelleFrais;

	public TypeFrais() {
	}

	public TypeFrais(String typeFrais) {
		this.typeFrais = typeFrais;
	}

	public TypeFrais(String typeFrais, String libelleFrais, String alibelleFrais) {
		this.typeFrais = typeFrais;
		this.libelleFrais = libelleFrais;
		this.alibelleFrais = alibelleFrais;
	}

	@Id
	@Column(name = "TYPE_FRAIS", unique = true, nullable = false, length = 1)
	public String getTypeFrais() {
		return this.typeFrais;
	}

	public void setTypeFrais(String typeFrais) {
		this.typeFrais = typeFrais;
	}

	@Column(name = "LIBELLE_FRAIS", length = 60)
	public String getLibelleFrais() {
		return this.libelleFrais;
	}

	public void setLibelleFrais(String libelleFrais) {
		this.libelleFrais = libelleFrais;
	}

	@Column(name = "ALIBELLE_FRAIS", length = 120)
	public String getAlibelleFrais() {
		return this.alibelleFrais;
	}

	public void setAlibelleFrais(String alibelleFrais) {
		this.alibelleFrais = alibelleFrais;
	}

}
