package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeOrganisme generated by hbm2java
 */
@Entity
@Table(name = "type_organisme", catalog = "ministere")
public class TypeOrganisme implements java.io.Serializable {

	private String codeTypeOrganisme;
	private String codeCleTypeOrganisme;
	private String libelleTypeOrganisme;
	private String alibelleTypeOrganisme;
	private Set<Organisme> organismes = new HashSet<Organisme>(0);

	public TypeOrganisme() {
	}

	public TypeOrganisme(String codeTypeOrganisme) {
		this.codeTypeOrganisme = codeTypeOrganisme;
	}

	public TypeOrganisme(String codeTypeOrganisme, String codeCleTypeOrganisme,
			String libelleTypeOrganisme, String alibelleTypeOrganisme,
			Set<Organisme> organismes) {
		this.codeTypeOrganisme = codeTypeOrganisme;
		this.codeCleTypeOrganisme = codeCleTypeOrganisme;
		this.libelleTypeOrganisme = libelleTypeOrganisme;
		this.alibelleTypeOrganisme = alibelleTypeOrganisme;
		this.organismes = organismes;
	}

	@Id
	@Column(name = "CODE_TYPE_ORGANISME", unique = true, nullable = false, length = 1)
	public String getCodeTypeOrganisme() {
		return this.codeTypeOrganisme;
	}

	public void setCodeTypeOrganisme(String codeTypeOrganisme) {
		this.codeTypeOrganisme = codeTypeOrganisme;
	}

	@Column(name = "CODE_CLE_TYPE_ORGANISME", length = 6)
	public String getCodeCleTypeOrganisme() {
		return this.codeCleTypeOrganisme;
	}

	public void setCodeCleTypeOrganisme(String codeCleTypeOrganisme) {
		this.codeCleTypeOrganisme = codeCleTypeOrganisme;
	}

	@Column(name = "LIBELLE_TYPE_ORGANISME", length = 60)
	public String getLibelleTypeOrganisme() {
		return this.libelleTypeOrganisme;
	}

	public void setLibelleTypeOrganisme(String libelleTypeOrganisme) {
		this.libelleTypeOrganisme = libelleTypeOrganisme;
	}

	@Column(name = "ALIBELLE_TYPE_ORGANISME", length = 120)
	public String getAlibelleTypeOrganisme() {
		return this.alibelleTypeOrganisme;
	}

	public void setAlibelleTypeOrganisme(String alibelleTypeOrganisme) {
		this.alibelleTypeOrganisme = alibelleTypeOrganisme;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeOrganisme")
	public Set<Organisme> getOrganismes() {
		return this.organismes;
	}

	public void setOrganismes(Set<Organisme> organismes) {
		this.organismes = organismes;
	}

}
