package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "ministere")
public class Utilisateur implements java.io.Serializable {

	private String cinUtilisateur;
	private Profil profil;
	private String nomUtilisateur;
	private String anomUtilisateur;
	private String prenomUtilisateur;
	private String aprenomUtilisateur;
	private String loginUtilisateur;
	private String mdpUtilisateur;

	public Utilisateur() {
	}

	public Utilisateur(String cinUtilisateur, Profil profil) {
		this.cinUtilisateur = cinUtilisateur;
		this.profil = profil;
	}

	public Utilisateur(String cinUtilisateur, Profil profil,
			String nomUtilisateur, String anomUtilisateur,
			String prenomUtilisateur, String aprenomUtilisateur,
			String loginUtilisateur, String mdpUtilisateur) {
		this.cinUtilisateur = cinUtilisateur;
		this.profil = profil;
		this.nomUtilisateur = nomUtilisateur;
		this.anomUtilisateur = anomUtilisateur;
		this.prenomUtilisateur = prenomUtilisateur;
		this.aprenomUtilisateur = aprenomUtilisateur;
		this.loginUtilisateur = loginUtilisateur;
		this.mdpUtilisateur = mdpUtilisateur;
	}

	@Id
	@Column(name = "CIN_UTILISATEUR", unique = true, nullable = false, length = 10)
	public String getCinUtilisateur() {
		return this.cinUtilisateur;
	}

	public void setCinUtilisateur(String cinUtilisateur) {
		this.cinUtilisateur = cinUtilisateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_PROFIL", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@Column(name = "NOM_UTILISATEUR", length = 15)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "ANOM_UTILISATEUR", length = 30)
	public String getAnomUtilisateur() {
		return this.anomUtilisateur;
	}

	public void setAnomUtilisateur(String anomUtilisateur) {
		this.anomUtilisateur = anomUtilisateur;
	}

	@Column(name = "PRENOM_UTILISATEUR", length = 15)
	public String getPrenomUtilisateur() {
		return this.prenomUtilisateur;
	}

	public void setPrenomUtilisateur(String prenomUtilisateur) {
		this.prenomUtilisateur = prenomUtilisateur;
	}

	@Column(name = "APRENOM_UTILISATEUR", length = 30)
	public String getAprenomUtilisateur() {
		return this.aprenomUtilisateur;
	}

	public void setAprenomUtilisateur(String aprenomUtilisateur) {
		this.aprenomUtilisateur = aprenomUtilisateur;
	}

	@Column(name = "LOGIN_UTILISATEUR", length = 40)
	public String getLoginUtilisateur() {
		return this.loginUtilisateur;
	}

	public void setLoginUtilisateur(String loginUtilisateur) {
		this.loginUtilisateur = loginUtilisateur;
	}

	@Column(name = "MDP_UTILISATEUR", length = 10)
	public String getMdpUtilisateur() {
		return this.mdpUtilisateur;
	}

	public void setMdpUtilisateur(String mdpUtilisateur) {
		this.mdpUtilisateur = mdpUtilisateur;
	}

}
