package tn.ministere.entity;

// Generated 26 mai 2014 14:49:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name = "zone", catalog = "ministere")
public class Zone implements java.io.Serializable {

	private String codeZone;
	private String libelleZone;
	private String alibelleZone;
	private Set<PaysDestination> paysDestinations = new HashSet<PaysDestination>(
			0);

	public Zone() {
	}

	public Zone(String codeZone) {
		this.codeZone = codeZone;
	}

	public Zone(String codeZone, String libelleZone, String alibelleZone,
			Set<PaysDestination> paysDestinations) {
		this.codeZone = codeZone;
		this.libelleZone = libelleZone;
		this.alibelleZone = alibelleZone;
		this.paysDestinations = paysDestinations;
	}

	@Id
	@Column(name = "CODE_ZONE", unique = true, nullable = false, length = 2)
	public String getCodeZone() {
		return this.codeZone;
	}

	public void setCodeZone(String codeZone) {
		this.codeZone = codeZone;
	}

	@Column(name = "LIBELLE_ZONE", length = 60)
	public String getLibelleZone() {
		return this.libelleZone;
	}

	public void setLibelleZone(String libelleZone) {
		this.libelleZone = libelleZone;
	}

	@Column(name = "ALIBELLE_ZONE", length = 120)
	public String getAlibelleZone() {
		return this.alibelleZone;
	}

	public void setAlibelleZone(String alibelleZone) {
		this.alibelleZone = alibelleZone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zone")
	public Set<PaysDestination> getPaysDestinations() {
		return this.paysDestinations;
	}

	public void setPaysDestinations(Set<PaysDestination> paysDestinations) {
		this.paysDestinations = paysDestinations;
	}

}
